INSERT INTO allcourses (coursecode,coursename,courseyear) VALUES ("CS 313","Intermediate Computer Programming",2);
INSERT INTO allcourses (coursecode,coursename,courseyear) VALUES ("Econ 201","Macroeconomics",2);
INSERT INTO allcourses (coursecode,coursename,courseyear) VALUES ("Eng 101","Physics 101",2);
INSERT INTO allcourses (coursecode,coursename,courseyear) VALUES ("CS 341","Web Technologies",3);
INSERT INTO allcourses (coursecode,coursename,courseyear) VALUES ("CS 101","Introduction to Computer Programming",1);
INSERT INTO allcourses (coursecode,coursename,courseyear) VALUES ("Econ 101","Microeconomics",2);
INSERT INTO allcourses (coursecode,coursename,courseyear) VALUES ("Eng 251","Circuits",2);
INSERT INTO allcourses (coursecode,coursename,courseyear) VALUES ("CS 386","Software Engineering",3);
INSERT INTO allcourses (coursecode,coursename,courseyear) VALUES ("CS 221","Database Management",2);
INSERT INTO allcourses (coursecode,coursename,courseyear) VALUES ("BA 201","Financial Accounting",2);
INSERT INTO allcourses (coursecode,coursename,courseyear) VALUES ("CS 321","Advanced Databases",4);
INSERT INTO allcourses (coursecode,coursename,courseyear) VALUES ("BA 101","Organizational Behaviour",1);
INSERT INTO allcourses (coursecode,coursename,courseyear) VALUES ("MD 101","Biology 1",1);
